sudo: required
dist: bionic
language: csharp
mono: none
dotnet:5.0
services: docker
before_install:
  - cd 03_RestWithASPNETUdemy_MainSolution/
  - echo "Tamo na pasta certa! - We are in the right folder!"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  scrpt:
    docker tag rest-with-asp-net-udemy-db: latest $DOCKER_USERNAME/rest-with-asp-net-udemy-db:$TRAVIS_JOB_ID;
    docker tag rest-with-asp-net-udemy: latest $DOCKER_USERNAME/rest-with-asp-net-udemy:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/rest-with-asp-net-udemy-db: $TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/rest-with-asp-net-udemy: $TRAVIS_JOB_ID;
  on:
    branch: master
notifications:
  email: false